# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Loaa2CgpG05S44S1FK0xBAjaR5tNbd8A
"""

import numpy as np
from scipy.stats import bernoulli
import random
sample_size = 100000
E, not_E = 0, 0
prob_E = 0.05 #given
sample = bernoulli.rvs(size = sample_size, p = prob_E)
for i in range(sample_size):
  if sample[i] == 1:
    E += 1
  elif sample[i] == 0:
    not_E += 1
p_E = E/sample_size
p_not_E = not_E/sample_size
print("For the given probability of P(E) = %f, the probability of not E i.e, P(E') = %f"%(p_E, p_not_E))
print("which is approximately equal to the theoretical value 0.95")

import matplotlib.pyplot as plt
from matplotlib_venn import venn2
A = set([0.05])
B = set([0.95])
v = venn2([A,B], ('Pr(E)', 'Pr(-E)'))

v.get_label_by_id('10').set_text('\n'.join(map(str,A)))
v.get_label_by_id('01').set_text('\n'.join(map(str,B)))
v.get_patch_by_id('01').set_color('white')
plt.axis('on')
plt.show()


